spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "1.1"

account:
  message: "Welcome Bank Account QA Microservice"
  contactDetails:
    name: "Brk Bayramin (QA Lead)"
    email: "brkbyrmn@gmail.com"
  onCallSupport:
    - (555) 555-2222
    - (555) 555-1111