server:
  port: 9000
spring:
  application:
    name: "card"
  config:
    import: "optional:configserver:http://localhost:8071"
#  datasource:
#    url: jdbc:mysql://localhost:3307/carddb
#    username: root
#    password: root
#  jpa:
#    show-sql: true
#  sql:
#    init:
#      mode: always
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    h2:
      console:
        enabled: true
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      show-sql: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "card"
    description: "Card Service"
    version: "1.4"
  company:
    name: "Burak Dev"
    contact:
      phone: "123-456-7890"
      email: "burakbyrmn@gmail.com"

logging:
  level:
    com:
      horakhty:
        card: DEBUG