build:
  version: "1.2"

cards:
  message: "Welcome to Bank cards related local APIs "
  contactDetails:
    name: "ABC - Developer"
    email: "abc@eazybank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932
